// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWZVtN3smG94vk2aSwmmTwdWR7x0qbXHI',
    appId: '1:474291952842:web:846592508fdf87965a6833',
    messagingSenderId: '474291952842',
    projectId: 'modelday-3a4d1',
    authDomain: 'modelday-3a4d1.firebaseapp.com',
    storageBucket: 'modelday-3a4d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWZVtN3smG94vk2aSwmmTwdWR7x0qbXHI',
    appId: '1:474291952842:android:846592508fdf87965a6833',
    messagingSenderId: '474291952842',
    projectId: 'modelday-3a4d1',
    storageBucket: 'modelday-3a4d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDaQMmD-CBFuKU3WC2hFA8_w4VIb0bcJE',
    appId: '1:474291952842:ios:a182617500bb29b25a6833',
    messagingSenderId: '474291952842',
    projectId: 'modelday-3a4d1',
    storageBucket: 'modelday-3a4d1.firebasestorage.app',
    iosBundleId: 'com.example.newFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDaQMmD-CBFuKU3WC2hFA8_w4VIb0bcJE',
    appId: '1:474291952842:ios:a182617500bb29b25a6833',
    messagingSenderId: '474291952842',
    projectId: 'modelday-3a4d1',
    storageBucket: 'modelday-3a4d1.firebasestorage.app',
    iosBundleId: 'com.example.newFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWZVtN3smG94vk2aSwmmTwdWR7x0qbXHI',
    appId: '1:474291952842:web:846592508fdf87965a6833',
    messagingSenderId: '474291952842',
    projectId: 'modelday-3a4d1',
    authDomain: 'modelday-3a4d1.firebaseapp.com',
    storageBucket: 'modelday-3a4d1.firebasestorage.app',
  );
}
